#ifndef CATCH2_LIB_CONFIG_H
#define CATCH2_LIB_CONFIG_H

#define CATCH2_LIB_VERSION "1_00"

// Help macro
#define CATCH2_LIB_STRINGIZE(X) CATCH2_LIB_DO_STRINGIZE(X)
#define CATCH2_LIB_DO_STRINGIZE(X) #X

#endif // CATCH2_LIB_CONFIG_H

